#!/usr/bin/env python3
"""Generate random scenario YAML files for the bin-clearing puzzle.

Generated files are compatible with:
  - puzzles: python main.py scenario=generated/scenario_0000
  - isaaclabmpc: python examples/ur16e_reach_stand_blocks/planner.py --scenario <path>
"""

import argparse
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from simulators.placement import random_initial_state


def _float_list_representer(dumper, data):
    if isinstance(data, list) and all(isinstance(x, (int, float)) for x in data):
        return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=False)


class _InlineDumper(yaml.Dumper):
    pass


_InlineDumper.add_representer(list, _float_list_representer)


def _state_to_dict(state: dict, args) -> dict:
    target_pos  = [round(v, 6) for v in state["target_pos"].tolist()]
    target_quat = [round(v, 6) for v in state["target_quat"].tolist()]
    obstacles   = [
        {
            "pos":  [round(v, 6) for v in p.tolist()],
            "quat": [round(v, 6) for v in q.tolist()],
        }
        for p, q in zip(state["obstacle_pos"], state["obstacle_quat"])
    ]
    return {
        "n_obstacles":    args.n_obstacles,
        "bin_size":       args.bin_size,
        "wall_thickness": args.wall_thickness,
        "friction":       args.friction,
        "initial_state": {
            "target_pos":  target_pos,
            "target_quat": target_quat,
            "obstacles":   obstacles,
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=10,
                        help="Number of scenarios to generate")
    parser.add_argument("--n_obstacles", type=int, default=3)
    parser.add_argument("--bin_size", type=float, default=0.3,
                        help="Bin width and depth in metres (square)")
    parser.add_argument("--obj_size", type=float, default=0.05,
                        help="Object cube side length in metres")
    parser.add_argument("--wall_thickness", type=float, default=0.02)
    parser.add_argument("--friction", type=float, default=1.2)
    parser.add_argument("--stackable", action="store_true")
    parser.add_argument("--difficult_spawn", action="store_true")
    parser.add_argument("--seed", type=int, default=None,
                        help="Base random seed; scenario i uses seed+i. "
                             "Omit for non-reproducible output.")
    parser.add_argument("--outdir", type=str, default="conf/scenario/generated",
                        help="Output directory for YAML files")
    parser.add_argument("--visualize", action="store_true",
                        help="Save a top-down PNG for each scenario alongside the YAML")
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    for i in range(args.n):
        seed = args.seed + i if args.seed is not None else None
        state = random_initial_state(
            n_obstacles=args.n_obstacles,
            obj_size=args.obj_size,
            stackable=args.stackable,
            difficult_spawn=args.difficult_spawn,
            seed=seed,
            bin_w=args.bin_size,
            bin_d=args.bin_size,
        )
        data = _state_to_dict(state, args)
        path = os.path.join(args.outdir, f"scenario_{i:04d}.yaml")
        with open(path, "w") as f:
            f.write("# Generated by generate_scenarios.py\n")
            yaml.dump(data, f, Dumper=_InlineDumper, default_flow_style=False, sort_keys=False)
        print(f"  {path}")

        if args.visualize:
            import matplotlib.pyplot as plt
            from visualization import render_scenario
            fig = render_scenario(state, args.bin_size, args.bin_size,
                                  args.obj_size, args.wall_thickness,
                                  title=f"scenario_{i:04d}")
            vis_path = os.path.join(args.outdir, f"scenario_{i:04d}.png")
            fig.savefig(vis_path, dpi=100)
            plt.close(fig)
            print(f"  {vis_path}")

    print(f"\nGenerated {args.n} scenarios in {args.outdir}/")


if __name__ == "__main__":
    main()
