"""
pipeline.py  –  End-to-end scenario → puzzle planning → IsaacLab MPC pipeline.

Stages
------
1. Generate N random scenarios and save as YAMLs in conf/scenario/generated/.
2. For each scenario, run the puzzle planner (benchmark.py-style, direct API)
   and save successful solutions as JSON.
3. Tear down the IsaacLab AppLauncher (releases GPU context).
4. For each successful solution, run isaaclabmpc planner.py + world.py as
   subprocesses, collect rich telemetry, and log everything to WandB.

Usage
-----
# Default: 10 scenarios, 3 obstacles, IsaacLab + MCTS
python pipeline.py --config-name=pipeline

# Override scenario count / planner
python pipeline.py --config-name=pipeline n_scenarios=20 n_obstacles=5

# Different planner
python pipeline.py --config-name=pipeline planner=rrt

# Custom WandB project
python pipeline.py --config-name=pipeline wandb_project=my-project wandb_entity=myname
"""

import json
import os
import signal
import subprocess
import sys
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import yaml
import hydra
from omegaconf import DictConfig, OmegaConf
import wandb


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------

@dataclass
class PuzzleResult:
    scenario_idx: int
    scenario_name: str
    seed: int
    success: bool
    plan_length: int
    batch_calls: int
    total_pairs: int
    plan_time_s: float
    verify_rate: float = 0.0
    final_reward: float | None = None
    reward_components: dict | None = None
    replay_success: bool | None = None


@dataclass
class MpcResult:
    scenario_name: str
    success: bool
    steps_completed: int
    total_steps: int
    elapsed_time_s: float
    ee_trajectory: list | None = None
    block_positions_final: list | None = None
    step_completion_events: list | None = None
    mppi_cost_history: list | None = None


# ---------------------------------------------------------------------------
# Stage 1: Scenario generation
# ---------------------------------------------------------------------------

def _generate_scenarios(cfg: DictConfig) -> list[tuple[str, dict]]:
    """Generate N scenario YAMLs + PNGs. Returns list of (scenario_name, initial_state)."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from simulators.placement import random_initial_state
    from generate_scenarios import _state_to_dict, _InlineDumper
    from visualization import render_scenario

    outdir = Path("conf/scenario/generated")
    outdir.mkdir(parents=True, exist_ok=True)

    bin_size = cfg.get('bin_size', 0.3)
    obj_size = cfg.get('obj_size', 0.05)
    wall_thickness = cfg.get('wall_thickness', 0.02)

    gen_args = SimpleNamespace(
        n_obstacles=cfg.n_obstacles,
        bin_size=bin_size,
        wall_thickness=wall_thickness,
        friction=cfg.get('friction', 1.2),
    )

    scenarios = []
    for i in range(cfg.n_scenarios):
        seed = cfg.seed + i if cfg.seed is not None else None
        state = random_initial_state(
            n_obstacles=cfg.n_obstacles,
            obj_size=obj_size,
            stackable=cfg.get('stackable', False),
            difficult_spawn=cfg.get('difficult_spawn', False),
            seed=seed,
            bin_w=bin_size,
            bin_d=bin_size,
            n_z_levels=cfg.get('n_z_levels', 1),
            target_z_level=cfg.get('target_z_level', None),
        )
        name = f"scenario_{i:04d}"
        yaml_path = outdir / f"{name}.yaml"
        data = _state_to_dict(state, gen_args)
        with open(yaml_path, 'w') as f:
            f.write("# Generated by pipeline.py\n")
            yaml.dump(data, f, Dumper=_InlineDumper, default_flow_style=False, sort_keys=False)

        fig = render_scenario(
            state, bin_size, bin_size, obj_size, wall_thickness,
            title=f"{name} (seed={seed})",
        )
        fig.savefig(outdir / f"{name}.png", dpi=120, bbox_inches='tight')
        plt.close(fig)

        scenarios.append((name, state))
        print(f"  [gen] {yaml_path}")

    print(f"\nGenerated {len(scenarios)} scenarios in {outdir}/")
    return scenarios


# ---------------------------------------------------------------------------
# Stage 2 helpers (benchmark.py-style)
# ---------------------------------------------------------------------------

def _render_state_image(state: dict, bin_size: float, obj_size: float,
                        wall_thickness: float) -> 'wandb.Image':
    from visualization import render_scenario
    fig = render_scenario(state, bin_size, bin_size, obj_size, wall_thickness)
    return wandb.Image(fig)


def _get_final_state(env, plan, initial_state):
    """Execute plan sequentially. Returns (final_state, force_traces)."""
    state = initial_state
    force_traces = []
    for action in plan:
        (state, _, _), = env.batch_evaluate([(state, action)])
        if hasattr(env, 'force_trace'):
            force_traces.append(list(env.force_trace))
    return state, force_traces


def _plan_scenario(env, cfg: DictConfig, scenario_idx: int, scenario_name: str,
                   initial_state: dict, seed: int) -> tuple[PuzzleResult, list | None]:
    """Run one planning attempt. Returns (PuzzleResult, plan_or_None)."""
    print(f'\n[Scenario {scenario_idx + 1}/{cfg.n_scenarios}] {scenario_name} seed={seed}')

    env.reset_sim_counters()
    from planner import _PlannerBase
    planner = _PlannerBase.from_cfg(env, cfg, seed)

    t0 = time.time()
    plan = planner.plan(initial_state, verbose=cfg.debug)
    plan_time = time.time() - t0

    success = plan is not None and len(plan) > 0
    result = PuzzleResult(
        scenario_idx=scenario_idx,
        scenario_name=scenario_name,
        seed=seed,
        success=success,
        plan_length=len(plan) if success else 0,
        batch_calls=env.batch_calls,
        total_pairs=env.total_pairs,
        plan_time_s=plan_time,
    )

    status = 'SUCCESS' if success else 'FAILED'
    print(f'  {status} | plan_len={result.plan_length} | '
          f'batch_calls={result.batch_calls} | time={plan_time:.1f}s')

    if not success:
        return result, None

    verify_successes, _, verify_rate, verify_passed = planner.verify(plan, initial_state)
    result.verify_rate = verify_rate
    print(f'  Verify: {verify_successes}/{env.n_envs} ({verify_rate:.0%}) — '
          f'{"PASS" if verify_passed else "FAIL"}')

    return result, plan


def _log_puzzle_wandb(result: PuzzleResult, initial_state, bin_size: float, obj_size: float,
                      wall_thickness: float, force_threshold: float | None,
                      plan, force_traces, all_results: list[PuzzleResult], step: int):
    """Log per-scenario puzzle metrics to WandB."""
    import matplotlib.pyplot as plt

    log = {
        'puzzles/success':       int(result.success),
        'puzzles/verify_rate':   result.verify_rate,
        'puzzles/plan_length':   result.plan_length,
        'puzzles/batch_calls':   result.batch_calls,
        'puzzles/total_pairs':   result.total_pairs,
        'puzzles/plan_time_s':   result.plan_time_s,
        'puzzles/seed':          result.seed,
        'puzzles/initial_state': _render_state_image(initial_state, bin_size, obj_size, wall_thickness),
    }
    if result.final_reward is not None:
        log['puzzles/final_reward'] = result.final_reward
    if result.replay_success is not None:
        log['puzzles/replay_success'] = int(result.replay_success)
    wandb.log(log, step=step)

    # Reward progress chart
    rewards = [(r.scenario_idx, r.final_reward) for r in all_results if r.final_reward is not None]
    if rewards:
        xs, ys = zip(*rewards)
        best = [max(ys[:k+1]) for k in range(len(ys))]
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.plot(xs, ys, 'o--', color='tab:blue', alpha=0.5, label='reward')
        ax.plot(xs, best, '-', color='tab:orange', linewidth=2, label='best so far')
        ax.set_xlabel('scenario')
        ax.set_ylabel('final reward')
        ax.set_title('Puzzle reward over scenarios')
        ax.legend()
        fig.tight_layout()
        wandb.log({'puzzles/reward_progress': wandb.Image(fig)}, step=step)
        plt.close(fig)

    if result.reward_components is not None:
        fig, ax = plt.subplots(figsize=(5, 3))
        keys = list(result.reward_components.keys())
        vals = list(result.reward_components.values())
        ax.bar(keys, vals, color=['tab:green' if v >= 0 else 'tab:red' for v in vals])
        ax.axhline(0, color='black', linewidth=0.8)
        ax.set_title(f'Reward components — {result.scenario_name}')
        fig.tight_layout()
        wandb.log({'puzzles/reward_breakdown': wandb.Image(fig)}, step=step)
        plt.close(fig)

    if force_traces and plan:
        fig, ax = plt.subplots(figsize=(8, 3))
        flat = [f for trace in force_traces for f in trace]
        boundaries = [0]
        for trace in force_traces:
            boundaries.append(boundaries[-1] + len(trace))
        ax.plot(flat, color='tab:blue', linewidth=1.0)
        for b in boundaries[1:-1]:
            ax.axvline(b, color='gray', linewidth=0.7, linestyle='--')
        if force_threshold and force_threshold > 0:
            ax.axhline(force_threshold, color='tab:red', linewidth=1.0, linestyle='--',
                       label=f'threshold ({force_threshold:.0f} N)')
            ax.legend(fontsize=8)
        label_y = max(flat) * 0.92 if flat else 1.0
        for b, action in zip(boundaries, plan):
            ax.text(b + 0.3, label_y, action['action_type'], fontsize=6, color='gray')
        ax.set_xlabel('physics step')
        ax.set_ylabel('contact force (N)')
        ax.set_title(f'Contact force — {result.scenario_name}')
        fig.tight_layout()
        wandb.log({'puzzles/contact_force': wandb.Image(fig)}, step=step)
        plt.close(fig)


# ---------------------------------------------------------------------------
# Stage 3: IsaacLab MPC subprocess runner
# ---------------------------------------------------------------------------

def _run_isaaclabmpc(scenario_name: str, scenario_yaml: Path, solution_json: Path,
                     out_dir: Path, cfg: DictConfig) -> MpcResult:
    """Launch planner.py + world.py subprocesses. Returns MpcResult."""
    ilab_dir = Path(cfg.isaaclabmpc_dir)
    result_json = out_dir / 'isaaclabmpc_results' / f'{scenario_name}.json'
    telemetry_json = out_dir / 'telemetry' / f'{scenario_name}_planner.json'
    planner_log = out_dir / 'logs' / f'{scenario_name}_planner.txt'
    world_log = out_dir / 'logs' / f'{scenario_name}_world.txt'

    python = sys.executable

    planner_cmd = [
        python,
        str(ilab_dir / 'planner.py'),
        '--scenario', str(scenario_yaml),
        '--solution_path', str(solution_json),
        '--telemetry_path', str(telemetry_json),
    ]
    world_cmd = [
        python,
        str(ilab_dir / 'world.py'),
        '--headless',
        '--scenario', str(scenario_yaml),
        '--n_steps', str(cfg.isaaclabmpc_n_steps),
        '--output_path', str(result_json),
    ]

    print(f'\n[MPC] {scenario_name}: launching planner …')
    with open(planner_log, 'w') as pf:
        planner_proc = subprocess.Popen(
            planner_cmd,
            cwd=str(ilab_dir.parent.parent),
            stdout=pf, stderr=subprocess.STDOUT,
        )

    # Give the zerorpc server time to bind before world connects
    time.sleep(3)

    print(f'[MPC] {scenario_name}: launching world …')
    with open(world_log, 'w') as wf:
        world_proc = subprocess.Popen(
            world_cmd,
            cwd=str(ilab_dir.parent.parent),
            stdout=wf, stderr=subprocess.STDOUT,
        )

    timed_out = False
    try:
        world_proc.wait(timeout=cfg.isaaclabmpc_timeout_s)
    except subprocess.TimeoutExpired:
        print(f'[MPC] {scenario_name}: TIMEOUT after {cfg.isaaclabmpc_timeout_s}s')
        world_proc.kill()
        timed_out = True
    finally:
        planner_proc.send_signal(signal.SIGTERM)
        try:
            planner_proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            planner_proc.kill()

    result_data = {}
    if result_json.exists():
        with open(result_json) as f:
            result_data = json.load(f)

    telemetry_data = {}
    if telemetry_json.exists():
        with open(telemetry_json) as f:
            telemetry_data = json.load(f)

    mpc_result = MpcResult(
        scenario_name=scenario_name,
        success=result_data.get('success', False) and not timed_out,
        steps_completed=result_data.get('steps_completed', 0),
        total_steps=result_data.get('total_steps', 0),
        elapsed_time_s=result_data.get('elapsed_time_s', 0.0),
        ee_trajectory=result_data.get('ee_trajectory'),
        block_positions_final=result_data.get('block_positions_final'),
        step_completion_events=result_data.get('step_completion_events'),
        mppi_cost_history=telemetry_data.get('mppi_cost_history'),
    )

    status = 'SUCCESS' if mpc_result.success else ('TIMEOUT' if timed_out else 'FAILED')
    print(f'[MPC] {scenario_name}: {status} — '
          f'{mpc_result.steps_completed}/{mpc_result.total_steps} steps '
          f'in {mpc_result.elapsed_time_s:.1f}s')
    return mpc_result


def _log_mpc_wandb(result: MpcResult, step: int):
    """Log per-scenario MPC metrics to WandB."""
    import matplotlib.pyplot as plt

    log = {
        'isaaclabmpc/success':          int(result.success),
        'isaaclabmpc/steps_completed':  result.steps_completed,
        'isaaclabmpc/total_steps':      result.total_steps,
        'isaaclabmpc/elapsed_time_s':   result.elapsed_time_s,
    }
    if result.total_steps > 0:
        log['isaaclabmpc/step_rate'] = result.steps_completed / result.total_steps

    if result.ee_trajectory:
        traj = np.array(result.ee_trajectory)
        fig, ax = plt.subplots(figsize=(8, 3))
        ts = list(range(len(traj)))
        for j, label in enumerate(['x', 'y', 'z']):
            ax.plot(ts, traj[:, j], label=label)
        ax.set_xlabel('sample (every 50 sim steps)')
        ax.set_ylabel('EE position (m)')
        ax.set_title(f'EE trajectory — {result.scenario_name}')
        ax.legend()
        fig.tight_layout()
        log['isaaclabmpc/ee_trajectory'] = wandb.Image(fig)
        plt.close(fig)

    if result.mppi_cost_history:
        fig, ax = plt.subplots(figsize=(8, 3))
        ax.plot(result.mppi_cost_history, color='tab:purple', linewidth=1.0)
        ax.set_xlabel('MPPI iteration')
        ax.set_ylabel('min cost')
        ax.set_title(f'MPPI cost — {result.scenario_name}')
        fig.tight_layout()
        log['isaaclabmpc/mppi_cost_history'] = wandb.Image(fig)
        plt.close(fig)

    if result.block_positions_final:
        pos = np.array(result.block_positions_final)
        fig, ax = plt.subplots(figsize=(5, 4))
        ax.scatter(pos[:, 0], pos[:, 1], c=pos[:, 2], cmap='viridis',
                   s=80, zorder=3, edgecolors='k', linewidths=0.5)
        for j, (x, y, _) in enumerate(pos):
            ax.text(x, y, str(j), fontsize=7, ha='center', va='center', color='white', zorder=4)
        ax.set_xlabel('x (m)')
        ax.set_ylabel('y (m)')
        ax.set_title(f'Final block positions — {result.scenario_name}')
        fig.tight_layout()
        log['isaaclabmpc/block_positions_final'] = wandb.Image(fig)
        plt.close(fig)

    wandb.log(log, step=step)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

@hydra.main(version_base=None, config_path="conf", config_name="pipeline")
def main(cfg: DictConfig) -> None:
    if cfg.simulator.name == 'isaaclab':
        os.environ['ISAACLAB_HEADLESS'] = '1'

    # ------------------------------------------------------------------
    # Stage 1: Generate scenarios (no simulator needed)
    # ------------------------------------------------------------------
    print('\n' + '=' * 60)
    print('Stage 1: Generating scenarios')
    print('=' * 60)
    scenarios = _generate_scenarios(cfg)

    # ------------------------------------------------------------------
    # Build env for Stage 2
    # ------------------------------------------------------------------
    print('\n' + '=' * 60)
    print(f'Building {cfg.simulator.name} env: {cfg.n_obstacles} obstacles, '
          f'{cfg.parallel_envs} parallel envs')
    print('=' * 60)
    from simulators import build_env
    env = build_env(cfg, n_envs=cfg.parallel_envs, show_viewer=False, viewer_mode='headless')

    # Init WandB after the simulator — AppLauncher process-level setup can
    # corrupt wandb's upload thread if wandb is initialised first.
    wandb.init(
        project=cfg.wandb_project,
        entity=cfg.wandb_entity if cfg.wandb_entity else None,
        name=cfg.wandb_run_name if cfg.wandb_run_name else None,
        config=OmegaConf.to_container(cfg, resolve=True),
    )
    while wandb.run is None:
        time.sleep(1)

    run_id = wandb.run.id
    out_dir = Path(cfg.output_dir) / run_id
    (out_dir / 'solutions').mkdir(parents=True, exist_ok=True)
    (out_dir / 'isaaclabmpc_results').mkdir(parents=True, exist_ok=True)
    (out_dir / 'telemetry').mkdir(parents=True, exist_ok=True)
    (out_dir / 'logs').mkdir(parents=True, exist_ok=True)
    print(f'\nOutput directory: {out_dir}')

    bin_size       = env.bin_w
    obj_size       = env._OBJ_SIZE
    wall_thickness = env.wall_thickness
    force_threshold = getattr(env, 'force_threshold', None)

    # ------------------------------------------------------------------
    # Stage 2: Puzzle planning
    # ------------------------------------------------------------------
    print('\n' + '=' * 60)
    print('Stage 2: Puzzle planning')
    print('=' * 60)

    from main import save_solution

    puzzle_results: list[PuzzleResult] = []
    successful: list[tuple[str, dict, Path]] = []

    for i, (scenario_name, initial_state) in enumerate(scenarios):
        seed = (cfg.seed + i) if cfg.seed is not None else i

        result, plan = _plan_scenario(env, cfg, i, scenario_name, initial_state, seed)

        force_traces = []
        if plan is not None:
            final_state, force_traces = _get_final_state(env, plan, initial_state)
            result.reward_components = env.compute_reward_components(final_state)
            result.final_reward = sum(result.reward_components.values())
            result.replay_success = env.is_goal(final_state)

            solution_path = out_dir / 'solutions' / f'{scenario_name}.json'
            save_solution(str(solution_path), plan, initial_state, cfg, env)
            successful.append((scenario_name, initial_state, solution_path))

        puzzle_results.append(result)
        _log_puzzle_wandb(
            result, initial_state,
            bin_size, obj_size, wall_thickness, force_threshold,
            plan, force_traces, puzzle_results, i,
        )

    n_puzzle_success = len(successful)
    print(f'\nPuzzle planning: {n_puzzle_success}/{cfg.n_scenarios} successful')

    # ------------------------------------------------------------------
    # Tear down IsaacLab before launching isaaclabmpc subprocesses
    # ------------------------------------------------------------------
    if hasattr(env, 'close'):
        env.close()
    del env
    if cfg.simulator.name == 'isaaclab':
        import simulators.isaaclab_env as _ilab
        _ilab.simulation_app.close(skip_cleanup=True)
        print('\n[pipeline] IsaacLab AppLauncher closed.')

    # ------------------------------------------------------------------
    # Stage 3: IsaacLab MPC
    # ------------------------------------------------------------------
    print('\n' + '=' * 60)
    print(f'Stage 3: IsaacLab MPC ({n_puzzle_success} scenarios)')
    print('=' * 60)

    mpc_results: list[MpcResult] = []

    for i, (scenario_name, initial_state, solution_path) in enumerate(successful):
        scenario_yaml = Path('conf/scenario/generated') / f'{scenario_name}.yaml'
        puzzle_idx = next(r.scenario_idx for r in puzzle_results if r.scenario_name == scenario_name)

        mpc_result = _run_isaaclabmpc(
            scenario_name, scenario_yaml, solution_path, out_dir, cfg
        )
        mpc_results.append(mpc_result)
        _log_mpc_wandb(mpc_result, puzzle_idx)

    # ------------------------------------------------------------------
    # Stage 4: Summary
    # ------------------------------------------------------------------
    n_mpc_success = sum(1 for r in mpc_results if r.success)

    print('\n' + '=' * 60)
    print(f'Pipeline complete.')
    print(f'  Scenarios generated: {cfg.n_scenarios}')
    print(f'  Puzzle success:      {n_puzzle_success}/{cfg.n_scenarios} '
          f'({n_puzzle_success/cfg.n_scenarios:.0%})')
    print(f'  MPC success:         {n_mpc_success}/{n_puzzle_success} '
          f'({n_mpc_success/max(n_puzzle_success, 1):.0%} of puzzle successes)')
    print('=' * 60)

    wandb.run.summary.update({
        'n_scenarios':                     cfg.n_scenarios,
        'n_puzzle_success':                n_puzzle_success,
        'n_mpc_success':                   n_mpc_success,
        'puzzles_success_rate':            n_puzzle_success / cfg.n_scenarios,
        'isaaclabmpc_success_rate':        n_mpc_success / cfg.n_scenarios,
        'isaaclabmpc_of_puzzle_rate':      n_mpc_success / max(n_puzzle_success, 1),
    })

    sc_artifact = wandb.Artifact('scenarios', type='dataset')
    sc_artifact.add_dir('conf/scenario/generated')
    wandb.log_artifact(sc_artifact)

    sol_artifact = wandb.Artifact('solutions', type='dataset')
    sol_artifact.add_dir(str(out_dir / 'solutions'))
    wandb.log_artifact(sol_artifact)

    wandb.finish()


if __name__ == '__main__':
    main()
